### ISSUE TITLE
for v2.0.1 score api.

### ISSUE THREAD

**Issue by SummerWQM** [SiftScience/sift-php#50]
curlUlr = https://api.siftscience.com/v204/score/1?api_key=abc&abuse_types=payment_abuse%2Cpromotion_abuse+%2Caccount_abuse%2Ccontent_abuse
will get error.

but: 
only support : https://api.siftscience.com/v204/score/1?api_key=abc&abuse_types=payment_abuse,promotion_abuse,account_abuse,content_abuse

**Comment by quanpod** [comment]
Hi @SummerWQM - can you provide additional clarity around what issue you're experiencing here and what error you're seeing when you call the Score API?

**Comment by ehrmann** [comment]
The issue is that there's a `+` in the first URL, so the abuse types get decoded as `payment_abuse`, `promotion_abuse ` (note the trailing space), `account_abuse`, and `content_abuse`.

There doesn't seem to be a bug in the [code building](https://github.com/SiftScience/sift-php/blob/702a3bf724b37ae75226d830939a01c499f1b918/lib/SiftClient.php#L180) the `abuse_types` parameter, so the issue looks like an abuse type with a trailing space was passed into the score call.
